apiVersion: v1
kind: Service
metadata:
  name: ocr-api
  namespace: ai-llm
spec:
  selector:
    app.kubernetes.io/name: ocr
  ports:
  - name: http
    port: 8000
    targetPort: http
  type: ClusterIP
