apiVersion: v1
kind: Secret
metadata:
  name: grafana-telegram
  namespace: monitoring
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: REPLACE_WITH_TELEGRAM_BOT_TOKEN
  TELEGRAM_CHAT_ID: REPLACE_WITH_TELEGRAM_CHAT_ID
